name: Documentation

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev", "doc", "qdoc", "dev-*"]
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.510"

      - name: Install Package
        run: |
          python -m pip install "git+https://github.com/has2k1/plotnine-examples"
          python -m pip install "git+https://github.com/has2k1/quartodoc.git@numpydoc-renderer"
          python -m pip install ".[doc]"
          quarto add has2k1/issuey

      - name: Environment Information
        shell: bash
        run: |
          ls -la
          ls -la doc
          pip list

      - name: Build docs
        run: |
          make doc

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_site
